// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeEcuDPG8bqDvyGKjutSB_79bW0ycm4Ok',
    appId: '1:68338682729:web:c736f10f4cca5e277e8bf8',
    messagingSenderId: '68338682729',
    projectId: 'homeease-app1',
    authDomain: 'homeease-app1.firebaseapp.com',
    storageBucket: 'homeease-app1.firebasestorage.app',
    measurementId: 'G-HSVXXLD4LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2ZIfetOpbx7axb-1eRSj9WFedX5954M',
    appId: '1:68338682729:android:171f12d064c172097e8bf8',
    messagingSenderId: '68338682729',
    projectId: 'homeease-app1',
    storageBucket: 'homeease-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqFu4qK-IO9Ng7_Wjjvb_SqYrp5KnWBmA',
    appId: '1:68338682729:ios:09a3833031c3b7777e8bf8',
    messagingSenderId: '68338682729',
    projectId: 'homeease-app1',
    storageBucket: 'homeease-app1.firebasestorage.app',
    iosBundleId: 'com.example.flutterHomeServiceProviderAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqFu4qK-IO9Ng7_Wjjvb_SqYrp5KnWBmA',
    appId: '1:68338682729:ios:09a3833031c3b7777e8bf8',
    messagingSenderId: '68338682729',
    projectId: 'homeease-app1',
    storageBucket: 'homeease-app1.firebasestorage.app',
    iosBundleId: 'com.example.flutterHomeServiceProviderAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeEcuDPG8bqDvyGKjutSB_79bW0ycm4Ok',
    appId: '1:68338682729:web:f7672d4f95ee49b47e8bf8',
    messagingSenderId: '68338682729',
    projectId: 'homeease-app1',
    authDomain: 'homeease-app1.firebaseapp.com',
    storageBucket: 'homeease-app1.firebasestorage.app',
    measurementId: 'G-BT9QLKCQYB',
  );

}